name: Update charts

on:
  workflow_dispatch:
  push:
    paths:
      - first_day_analysis.csv
      - generate_trends.py
      - repo_barchart.py

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Generate charts
        run: |
          uv run generate_trends.py
          uv run repo_barchart.py

      - name: Commit charts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cost_trend.png log_cost_trend.png loc_trend.png repo_barchart.png
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update trend charts"
            git push
          fi
